{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rvest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rvest/rvest_{{ version }}.tar.gz
  sha256: 7d707c6b2994cf7b6c1d665bec872d2ef5c55f30e7c343c447a8a386a6049ca6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-glue
    - r-httr >=0.5
    - r-lifecycle >=1.0.0
    - r-magrittr
    - r-rlang >=1.0.0
    - r-selectr
    - r-tibble
    - r-withr
    - r-xml2 >=1.3
  run:
    - r-base
    - r-cli
    - r-glue
    - r-httr >=0.5
    - r-lifecycle >=1.0.0
    - r-magrittr
    - r-rlang >=1.0.0
    - r-selectr
    - r-tibble
    - r-withr
    - r-xml2 >=1.3

test:
  commands:
    - $R -e "library('rvest')"           # [not win]
    - "\"%R%\" -e \"library('rvest')\""  # [win]

about:
  home: http://rvest.tidyverse.org/, https://github.com/tidyverse/rvest
  license: MIT
  summary: Wrappers around the 'xml2' and 'httr' packages to make it easy to download, then manipulate, HTML and XML.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rvest
# Title: Easily Harvest (Scrape) Web Pages
# Version: 0.3.4
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Wrappers around the 'xml2' and 'httr' packages to make it easy to download, then manipulate, HTML and XML.
# License: GPL-3
# URL: http://rvest.tidyverse.org/, https://github.com/tidyverse/rvest
# BugReports: https://github.com/tidyverse/rvest/issues
# Depends: R (>= 3.2), xml2
# Imports: httr (>= 0.5), magrittr, selectr
# Suggests: covr, knitr, png, rmarkdown, spelling, stringi (>= 0.3.1), testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-15 19:45:39 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-05-15 20:10:30 UTC
