{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvest
  version: {{ version|replace("-", "_") }}

source:
  fn: rvest_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rvest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rvest/rvest_{{ version }}.tar.gz
  sha256: b10a87fa2d733f7c0fc567242ef0ab10a1a77d58d51796996cc0fd81381a556f

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-httr >=0.5
    - r-magrittr
    - r-selectr
    - r-xml2
  run:
    - r-base
    - r-httr >=0.5
    - r-magrittr
    - r-selectr
    - r-xml2

test:
  commands:
    - $R -e "library('rvest')"           # [not win]
    - "\"%R%\" -e \"library('rvest')\""  # [win]

about:
  home: https://github.com/hadley/rvest
  license: GPL-3
  summary: Wrappers around the 'xml2' and 'httr' packages to make it easy to download, then manipulate,
    HTML and XML.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
