{% set version = '0.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rvest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rvest/rvest_{{ version }}.tar.gz
  sha256: b10a87fa2d733f7c0fc567242ef0ab10a1a77d58d51796996cc0fd81381a556f

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-httr >=0.5
    - r-magrittr
    - r-selectr
    - r-xml2
  run:
    - r-base
    - r-httr >=0.5
    - r-magrittr
    - r-selectr
    - r-xml2

test:
  commands:
    - $R -e "library('rvest')"           # [not win]
    - "\"%R%\" -e \"library('rvest')\""  # [win]

about:
  home: http://rvest.tidyverse.org/, https://github.com/tidyverse/rvest
  license: GPL-3
  summary: Wrappers around the 'xml2' and 'httr' packages to make it easy to download, then manipulate,
    HTML and XML.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rvest
# Title: Easily Harvest (Scrape) Web Pages
# Version: 0.3.3
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Wrappers around the 'xml2' and 'httr' packages to make it easy to download, then manipulate, HTML and XML.
# License: GPL-3
# URL: http://rvest.tidyverse.org/, https://github.com/tidyverse/rvest
# BugReports: https://github.com/tidyverse/rvest/issues
# Depends: R (>= 3.1), xml2
# Imports: httr (>= 0.5), magrittr, selectr
# Suggests: covr, knitr, png, rmarkdown, spelling, stringi (>= 0.3.1), testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-29 21:47:17 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-04-11 07:22:44 UTC
