# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "uNcpiUEpLEcjydirDtfAeZgy9M4i6sq0pfie0iktXkdCWh209QfoitZ2mTP6wNDxYk/qAr5/KLYAsaHzX6uDL6tyx9ukUkvSFEyNy+6Ej7EgEXcL35osvHJP/EKsghjSaQseG4fCj5E3KKgBQb/yxRwVjmR7W49hX5c28O+0eVc3nB+ULhieSDbcgNChb8/N80vHevkvMm1ET7WyKUrwja57Zp8hM44Yo6+Owf/wgZdKnBAgZJFPaNMf0mOUCTXsGanNwbe5zYJnr6+fjhfHMM+onezkEs9QLLdLd+ArWHSrtlx9noFn+D1OwRGFbHxuUNu3HmoJjnzVpNOeAT/8dGn14oXmquRtxjsOX/aGRnaKDCHXGRCJbyjTKh0hACemG/xgh/5wZdQ2IsCTkou6kJyqctvpNBggv72p01t2TJbmgn9FQe0O/uR3jQtTutLGDjUrVwxgvPFZ9Mwbel4LENs9lkKvRf5pffg58vOgNgQCwCIA67vTnuEN5VGXVxZ5yxfQNoW6aW+8qG3JTAj1Vh5tNGDqZwpdU43esVDPqAGJtSBgAiJF9ISFsuEB1ZaNKP+MJQiL+I1jD2qVwkpoX/tqbFPwwFU2MMoEed7GPKkRvJ9YO84mJ2RGVawnp5SlxVHz+ExmK9jF2YRMFoIopt6ssGDhwil2797dScANV+s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
