# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "uNcpiUEpLEcjydirDtfAeZgy9M4i6sq0pfie0iktXkdCWh209QfoitZ2mTP6wNDxYk/qAr5/KLYAsaHzX6uDL6tyx9ukUkvSFEyNy+6Ej7EgEXcL35osvHJP/EKsghjSaQseG4fCj5E3KKgBQb/yxRwVjmR7W49hX5c28O+0eVc3nB+ULhieSDbcgNChb8/N80vHevkvMm1ET7WyKUrwja57Zp8hM44Yo6+Owf/wgZdKnBAgZJFPaNMf0mOUCTXsGanNwbe5zYJnr6+fjhfHMM+onezkEs9QLLdLd+ArWHSrtlx9noFn+D1OwRGFbHxuUNu3HmoJjnzVpNOeAT/8dGn14oXmquRtxjsOX/aGRnaKDCHXGRCJbyjTKh0hACemG/xgh/5wZdQ2IsCTkou6kJyqctvpNBggv72p01t2TJbmgn9FQe0O/uR3jQtTutLGDjUrVwxgvPFZ9Mwbel4LENs9lkKvRf5pffg58vOgNgQCwCIA67vTnuEN5VGXVxZ5yxfQNoW6aW+8qG3JTAj1Vh5tNGDqZwpdU43esVDPqAGJtSBgAiJF9ISFsuEB1ZaNKP+MJQiL+I1jD2qVwkpoX/tqbFPwwFU2MMoEed7GPKkRvJ9YO84mJ2RGVawnp5SlxVHz+ExmK9jF2YRMFoIopt6ssGDhwil2797dScANV+s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
