travis:
  secure:
    BINSTAR_TOKEN: uNcpiUEpLEcjydirDtfAeZgy9M4i6sq0pfie0iktXkdCWh209QfoitZ2mTP6wNDxYk/qAr5/KLYAsaHzX6uDL6tyx9ukUkvSFEyNy+6Ej7EgEXcL35osvHJP/EKsghjSaQseG4fCj5E3KKgBQb/yxRwVjmR7W49hX5c28O+0eVc3nB+ULhieSDbcgNChb8/N80vHevkvMm1ET7WyKUrwja57Zp8hM44Yo6+Owf/wgZdKnBAgZJFPaNMf0mOUCTXsGanNwbe5zYJnr6+fjhfHMM+onezkEs9QLLdLd+ArWHSrtlx9noFn+D1OwRGFbHxuUNu3HmoJjnzVpNOeAT/8dGn14oXmquRtxjsOX/aGRnaKDCHXGRCJbyjTKh0hACemG/xgh/5wZdQ2IsCTkou6kJyqctvpNBggv72p01t2TJbmgn9FQe0O/uR3jQtTutLGDjUrVwxgvPFZ9Mwbel4LENs9lkKvRf5pffg58vOgNgQCwCIA67vTnuEN5VGXVxZ5yxfQNoW6aW+8qG3JTAj1Vh5tNGDqZwpdU43esVDPqAGJtSBgAiJF9ISFsuEB1ZaNKP+MJQiL+I1jD2qVwkpoX/tqbFPwwFU2MMoEed7GPKkRvJ9YO84mJ2RGVawnp5SlxVHz+ExmK9jF2YRMFoIopt6ssGDhwil2797dScANV+s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
