travis:
  secure:
    BINSTAR_TOKEN: J8CUfsulum5jdbLQGXfd64FaQjqP+tkr05C2Uyf4FjLjfEqc0xPVP5xuoTnCXjqqO/v9K6EMieDTBEhmxZzA7CfxHCbxWTTx9nPxjgeEpEEbNiMwZ2PRYwEs7TNx8ERMsoiKjYJZtAgHGbTwBnL3Z22ZLTq23cLvPhBrB7WtN4SV9sJpV4R8rngR6SA4YNOvhvp41qqVySirHulkpiMF20OL4kjV8CxBIr8Nkxl+pwzWDHFE71LtkMuXSEkIqtYCjZvStyN9q1CD7ZuDWQW6kJSB/hH15Ci9WNT2u/GlilRCBy3P5N5J0isxo7XhhOT185UaUV9t4d4KlAiObaNUeJPUPyLGopLbNxvgAFKRJ9D1+xWgl80pTsHdUCGsNAECxV8GSJVZUDxuxR0bcP4m31vr7MMercxUToQl5h7SNCpOupb3w4UkUYRyS+jIN2olL131fzk5gh/Iofr1yE8PvsRvAUfL9rGUDZ74v4m047kJcBJAGCi4H17CWjy9kFwvW1mldWJXm68XVAARHk3GSRr8lCzSBdV4w2sKzfBfBcX6Gu5+zxUgLv/Fqg0/TfeKXAHUVgRNYe4J/IgRSUvV40nH0ADwdosK+II3EOZ6wgySX4pRI4DB0DY6RvW0TuvZlLg7DvTciNvhaIRIWJ8a7zWn3dcChksDH/LtwXB6GMo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
